python train.py \
-exp_name soft+hard/bert_emb/no_alpha/bert_transformer5_linear1024 \
-ext_ff_size 1024 \
-ext_layers 5 \
-mode test \
-visible_gpus 0 \
-gpu_ranks 0 \
-batch_size 30000 \
-test_from ../models/soft+hard/bert_emb/no_alpha/bert_transformer5_linear1024/model_step_47000.pt \
-block_trigram true \
